XMooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.views.generic import TemplateView

import xadmin
from XMooc.settings import MEDIA_ROOT  # , STATIC_ROOT
from users.views import IndexView


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),    # 配置成 加载 xadmin
    # url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$', IndexView.as_view(), name='index'),

    # 配置验证码url
    url(r'^captcha/', include('captcha.urls')),

    # 配置 UEditor 富文本编辑器 url
    url(r'^ueditor/', include('DjangoUeditor.urls')),

    # 配置 处理media下面静态文件的url
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # 配置 处理static下面静态文件的url
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),

    # users的url配置放到了app目录下
    url(r'^users/', include('users.urls', namespace='user')),

    # orginazitiom的url配置放到了app目录下
    url(r'^org/', include('organization.urls', namespace='org')),

    # courses的url配置放到了app目录下
    url(r'^courses/', include('courses.urls', namespace='course')),

    # operation 的url配置放到了app目录下
    url(r'^operation/', include('operation.urls', namespace='operation')),

]

# 配置 403 404 500 页面
handler403 = 'users.views.page_not_allow'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.server_error'

apps/courses/urls.py
from django.conf.urls import url, include

from .views import (CourseListView, CourseDetailView, CourseStudyView, CourseCommentView,
                    CourseAddcommentView, CourseVideoView)


urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='detail'),

    url(r'^study/(?P<course_id>\d+)/$', CourseStudyView.as_view(), name='study'),
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='comment'),
    url(r'^add_comment/$', CourseAddcommentView.as_view(), name='add_comment'),
    url(r'^video/(?P<video_id>.*?)/$', CourseVideoView.as_view(), name='video'),

]

apps/operation/urls.py
from django.conf.urls import url

from .views import UserAskView, FavView


urlpatterns = [
    url(r'^ask/$', UserAskView.as_view(), name='ask'),
    url(r'^fav/$', FavView.as_view(), name='fav'),
]

apps/organization/urls.py
from django.conf.urls import url, include
from .views import (OrglistView, OrghomeView, OrgcourseView, OrgdescView, OrgteacherView, TeacherListView,
                    TeacherDetailView)


urlpatterns = [
    url(r'^list/$', OrglistView.as_view(), name='list'),
    url(r'^home/(?P<org_id>\d+)/$', OrghomeView.as_view(), name='home'),
    url(r'^courses/(?P<org_id>\d+)/$', OrgcourseView.as_view(), name='courses'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgdescView.as_view(), name='desc'),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgteacherView.as_view(), name='teacher'),

    # 配置teacher 相关页面
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),

]

apps/users/urls.py
from django.conf.urls import url

from .views import (LoginView, LogoutView, RegisterView, ActiveView, ForgetpwdView, ResetpwdView, UserInfoView,
                    UpdateImageView, UpdatePasswdView, UpdateEmailView, UserInfoCourseView, UserInfoFavCoursesView,
                    UserInfoFavOrgsView, UserInfoFavTeachersView, UserInfoMessageView)


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<active_code>.*)/$', ActiveView.as_view(), name='user_active'),
    url(r'^forget/$', ForgetpwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<reset_code>.*)/$', ResetpwdView.as_view(), name='reset_pwd'),

    # 用户中心的url配置
    url(r'^info/$', UserInfoView.as_view(), name='info'),   # 用户信息页面显示或修改
    url(r'^image/upload/$', UpdateImageView.as_view(), name='update_image'),  # 更新用户头像
    url(r'^passwd/update/$', UpdatePasswdView.as_view(), name='passwd_update'),  # 更新用户密码
    url(r'^email/update/$', UpdateEmailView.as_view(), name='email_update'),  # 获取邮箱验证码以及更新用户邮箱

    url(r'^user_courses/$', UserInfoCourseView.as_view(), name='user_courses'),  # 获取我的课程
    url(r'^user_fav_courses/$', UserInfoFavCoursesView.as_view(), name='user_fav_courses'),  # 获取我收藏的课程
    url(r'^user_fav_orgs/$', UserInfoFavOrgsView.as_view(), name='user_fav_orgs'),  # 获取我收藏的课程机构
    url(r'^user_fav_teachers/$', UserInfoFavTeachersView.as_view(), name='user_fav_teachers'),  # 获取我收藏的老师

    url(r'^message/$', UserInfoMessageView.as_view(), name='message'),  # 加载用户消息
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/courses/models.py
from datetime import datetime

from django.db import models
from DjangoUeditor.models import UEditorField

from organization.models import CourseOrg, Teacher
# Create your models here.


class Course(models.Model):
    name = models.CharField(max_length=64, verbose_name="课程名称")
    desc = models.CharField(max_length=256, verbose_name="课程描述")
    course_org = models.ForeignKey(CourseOrg, verbose_name="课程机构")
    teacher = models.ForeignKey(Teacher, verbose_name="教师")
    # detail = models.TextField(verbose_name="课程详情")
    detail = UEditorField(width=600, height=300, imagePath="courses/ueditor/images/",
                    filePath="courses/ueditor/files/", default='', verbose_name="课程详情")
    degree_choices = (
        ('simple', '初级'),
        ('middle', '中级'),
        ('high', '高级'),
    )
    degree = models.CharField(max_length=16, choices=degree_choices, default='middle', verbose_name="课程难度")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")
    students = models.IntegerField(default=0, verbose_name="学习人数")
    fav_num = models.IntegerField(default=0, verbose_name="收藏人数")
    image = models.ImageField(max_length=128, upload_to='courses/%Y/%m', null=True, blank=True, verbose_name="封面图")
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    tags = models.CharField(max_length=64, default='', verbose_name="课程类别")
    course_info = models.CharField(max_length=128, default='', verbose_name="课程须知")
    course_harvest = models.CharField(max_length=128, default='', verbose_name="课程收获")
    is_banner = models.BooleanField(default=False, verbose_name="是否轮播")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    def get_lesson_num(self):
        """ 获取课程的章节数 """
        return self.lesson_set.all().count()

    def get_all_lesson(self):
        """ 获取课程的所有章节 """
        return self.lesson_set.all()

    def get_course_resource(self):
        """ 获取课程的所有资源 """
        return self.courseresource_set.all()

    def get_course_comment(self):
        """ 获取课程的评论 """
        return self.coursecomment_set.all()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey('Course', verbose_name="课程")
    name = models.CharField(max_length=128, verbose_name="章节名称")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def get_all_video(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey('Lesson', verbose_name="章节")
    name = models.CharField(max_length=128, verbose_name="视频名称")
    url = models.CharField(max_length=256, default='', verbose_name="url地址")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey('Course', verbose_name="课程")
    name = models.CharField(max_length=128, verbose_name="资料名称")
    download = models.FileField(max_length=128, upload_to='courses/resource/%Y/%m', verbose_name="下载")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/courses/views.py
import json

from django.shortcuts import render
from django.views.generic import View
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.db.models import Q

from .models import Course, Video
from operation.models import UserCourse, UserFavorite, CourseComment, UserMessage
from utils.mixin_utils import LoginRequiredMixin

# Create your views here.


class CourseListView(View):
    """
    课程列表页信息
    """
    def get(self, request):
        # 默认按照最新的排列
        all_courses = Course.objects.all().order_by('-add_time')

        # 搜索功能实现
        keywords = request.GET.get('keywords', '')
        if keywords:
            all_courses = all_courses.filter(
                Q(name__icontains=keywords) | Q(desc__icontains=keywords) |
                Q(detail__icontains=keywords) | Q(tags__icontains=keywords)
            )

        # 热门课程推荐
        hot_courses = all_courses.order_by('-click_nums')[:3]

        # 展昭指定的方式对queryset进行排序
        sort = request.GET.get('sort', '')
        if sort == 'hot':
            # 按照 热度 排列
            all_courses = all_courses.order_by('-click_nums')
        elif sort == 'students':
            all_courses = all_courses.order_by('-students')

        # 实现分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_courses, 6, request=request)

        courses = p.page(page)

        return render(request, 'course-list.html', {
            'courses': courses,
            'hot_courses': hot_courses,
            'sort': sort,
        })


class CourseDetailView(View):
    """
    课程详情页面
    """
    def get(self, request, course_id):
        # 找出这门课程
        course = Course.objects.get(id=int(course_id))

        # 每次请求一次这个页面， 课程的点击数 +1
        course.click_nums += 1
        course.save()

        # 找出学习这门课程的学生记录（取几个就是）
        user_courses = UserCourse.objects.filter(course=course)[:5]

        # 这个课程的所属机构
        course_org = course.course_org

        # 检查用户是否收藏该课程或则该机构
        fav_course = False
        fav_org = False
        if request.user.is_authenticated():
            user_fav = UserFavorite.objects.filter(user=request.user)
            if user_fav.filter(fav_type=1, fav_id=course.id):
                fav_course = True
            if user_fav.filter(fav_type=2, fav_id=course_org.id):
                fav_org = True

        # 课程相关推荐
        if course.tags:
            relate_courses = Course.objects.filter(tags=course.tags).order_by('-click_nums')[:1]
        else:
            relate_courses = []

        return render(request, 'course-detail.html', {
            'course': course,
            'user_courses': user_courses,
            'course_org': course_org,
            'fav_course': fav_course,
            'fav_org': fav_org,
            'relate_courses': relate_courses,

        })


class CourseStudyView(LoginRequiredMixin, View):
    """
    课程 学习 页面 信息
    """
    def get(self, request, course_id):
        # 找出这门课程
        course = Course.objects.get(id=int(course_id))

        # 每次点击开始学习， 这门课程的学习人数+1
        course.students += 1
        course.save()

        # 把 课程 与 用户绑定
        user_couses = UserCourse.objects.filter(user=request.user, course=course)
        if not user_couses:
            UserCourse.objects.create(user=request.user, course=course)

            # 给用户发消息
            message = "欢迎学习{course_name}， 希望你能学有所获".format(course_name=course.name)
            UserMessage.objects.create(user=request.user.id, message=message)

        # 课程相关推荐
        if course.tags:
            relate_courses = Course.objects.filter(tags=course.tags).exclude(id=course.id).order_by('-click_nums')[:3]
        else:
            relate_courses = []

        return render(request, 'course-video.html', {
            'course': course,
            'relate_courses': relate_courses,
        })


class CourseCommentView(LoginRequiredMixin, View):
    """
    课程 评论 页面 信息
    """
    def get(self, request, course_id):
        # 找出这门课程
        course = Course.objects.get(id=int(course_id))

        # 查找学过该课程的同学 学的其他课程
        # user_ids = [user_course.user.id for user_course in course.usercourse_set.all()]
        user_courses = UserCourse.objects.filter(course=course)
        user_ids = [user_course.user.id for user_course in user_courses]

        all_users_courses = UserCourse.objects.filter(user_id__in=user_ids)
        course_ids = [user_course.course.id for user_course in all_users_courses]
        relate_courses = Course.objects.filter(id__in=course_ids).order_by('-click_num')[:3]
        # if course.tags:
        #     relate_courses = Course.objects.filter(tags=course.tags).exclude(id=course.id).order_by('-click_nums')[:3]
        # else:
        #     relate_courses = []

        return render(request, 'course-comment.html', {
            'course': course,
            'relate_courses': relate_courses,
        })


class CourseVideoView(LoginRequiredMixin, View):
    """
    播放 视频
    """
    def get(self, request, video_id):
        # 找到这个视频
        video = Video.objects.get(id=int(video_id))

        # 找出这门课程
        course = video.lesson.course

        # 课程相关推荐
        if course.tags:
            relate_courses = Course.objects.filter(tags=course.tags).exclude(id=course.id).order_by('-click_nums')[:3]
        else:
            relate_courses = []

        return render(request, 'play-video.html', {
            'video': video,
            'course': course,
            'relate_courses': relate_courses,
        })


class CourseAddcommentView(View):
    """
    添加评论
    """
    def post(self, request):
        course_id = request.POST.get('course_id', '')
        comments = request.POST.get('comments', '')

        # 只有登陆后才能收藏
        if not request.user.is_authenticated():
            status = {'code': 1, 'msg': '用户未登录'}
            return HttpResponse(content=json.dumps(status), content_type='application/json')

        if course_id and comments:
            CourseComment.objects.create(user=request.user, course_id=course_id, comments=comments)
            status = {'code': 0, 'msg': '评论成功'}
        else:
            status = {'code': 1, 'msg': '评论失败'}

        return HttpResponse(content=json.dumps(status), content_type='application/json')

templates/courses/course-comment.html
{% extends 'base.html' %}
{% load static %}

{% block custom_title %}公开课视频信息 - 慕学在线网{% endblock %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
{% endblock %}

{% block custom_bread %}
     <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course:detail' course.id %}">课程详情</a>></li>
                    <li>章节信息</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }} 分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active" id="learnOn"  href="{% url 'course:study' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="active" href="{% url 'course:comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                        {% for comment in course.get_course_comment %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment.user.nick_name }}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                    </div>
                                </div>
                        </li>
                        {% endfor %}
                        </ul>
                    </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in course.get_course_resource %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% static '315464/courses?sort=publish' %}" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.user.image }}' width='80' height='80' />
                            </a>
                            <span class="tit">
                              <a href="{% static '315464/courses?sort=publish' %}" target="_blank">{{ course.teacher.name }}</a>
                            </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.course_info }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.course_harvest }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                            <!-- img 200 x 112 -->
                            <ul class="other-list">
                                {% for relate_course in relate_courses %}
                                    <li class="curr">
                                    <a href="{% url 'course:detail' relate_course.id %}" target="_blank">
                                        <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name }}">
                                        <span class="name autowrap">{{ relate_course.name }}</span>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>

{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(status) {
                if(status.code == 1){
                    if(status.msg == '用户未登录'){
                        window.location.href="{% url 'user:login' %}";
                    }else{
                        alert(status.msg)
                    }

                }else if(status.code == 0){
                    window.location.reload();//刷新当前页面.
                }
            }
        });
    });
</script>
{% endblock %}


</body>
</html>

templates/courses/play-video.html
{% extends 'base.html' %}
{% load static %}

{% block custom_title %}公开课视频信息 - 慕学在线网{% endblock %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">

  <link href="http://vjs.zencdn.net/6.4.0/video-js.css" rel="stylesheet">

{% endblock %}

{% block custom_bread %}
     <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course:detail' course.id %}">课程详情</a>></li>
                    <li>视频信息</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}
<div id="main">
        <div style="margin-top: 1%; margin-left: 20%; margin-bottom: 2%;">
            <video id="my-video" class="video-js" controls preload="auto" width="1000" height="660"
              poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
                <source src="{{ MEDIA_URL }}{{ video.url }}" type='video/mp4'>
                <p class="vjs-no-js">
                  To view this video please enable JavaScript, and consider upgrading to a web browser that
                  <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                </p>
            </video>
        </div>
    <div class="course-info-main clearfix w has-progress">
        <div class="content">
            <div class="mod-tab-menu">
                <ul class="course-menu clearfix">
                    <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:study' course.id %}"><span>章节</span></a></li>
                    <li><a id="commentOn" class="" href="{% url 'course:comment' course.id %}"><span>评论</span></a></li>
                </ul>
            </div>
            <div id="notice" class="clearfix">
                <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course.desc }}</a> </div>
            </div>

            <div class="mod-chapters">
            {% for lesson in course.get_all_lesson %}
                <div class="chapter chapter-active" >
                    <h3>
                        <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                    </h3>
                    <ul class="video">
                    {% for video in lesson.get_all_video %}
                        <li>
                        <a target="" href='{% url 'course:video' video.id %}' class="J-media-item studyvideo">{{ video.name }} ({{ video.learn_times }})
                            <i class="study-state"></i>
                        </a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
            {% endfor %}
            </div>

        </div>
        <div class="aside r">
            <div class="bd">

                <div class="box mb40">
                    <h4>资料下载</h4>
                    <ul class="downlist">
                        {% for resource in course.get_course_resource %}
                        <li>
                            <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                            <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="box mb40">
                    <h4>讲师提示</h4>
                    <div class="teacher-info">
                        <a href="{% static '315464/courses?sort=publish' %}" target="_blank">
                            <img src='{{ MEDIA_URL }}{{ course.teacher.user.image }}' width='80' height='80' />
                        </a>
                        <span class="tit">
                          <a href="{% static '315464/courses?sort=publish' %}" target="_blank">{{ course.teacher.name }}</a>
                        </span>
                        <span class="job">{{ course.teacher.work_position }}</span>
                    </div>
                    <div class="course-info-tip">
                        <dl class="first">
                            <dt>课程须知</dt>
                            <dd class="autowrap">{{ course.course_info }}</dd>
                        </dl>
                        <dl>
                            <dt>老师告诉你能学到什么？</dt>
                            <dd class="autowrap">{{ course.course_harvest }}</dd>
                        </dl>
                    </div>
                </div>


                <div class="cp-other-learned  js-comp-tabs">
                    <div class="cp-header clearfix">
                        <h2 class="cp-tit l">该课的同学还学过</h2>
                    </div>
                    <div class="cp-body">
                        <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                        <!-- img 200 x 112 -->
                        <ul class="other-list">
                            {% for relate_course in relate_courses %}
                                <li class="curr">
                                <a href="{% url 'course:detail' relate_course.id %}" target="_blank">
                                    <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name }}">
                                    <span class="name autowrap">{{ relate_course.name }}</span>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>

{% endblock %}