XMooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.views.generic import TemplateView

import xadmin
from XMooc.settings import MEDIA_ROOT  # , STATIC_ROOT
from users.views import IndexView


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),    # 配置成 加载 xadmin
    # url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$', IndexView.as_view(), name='index'),

    # 配置验证码url
    url(r'^captcha/', include('captcha.urls')),

    # 配置 UEditor 富文本编辑器 url
    url(r'^ueditor/', include('DjangoUeditor.urls')),

    # 配置 处理media下面静态文件的url
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # 配置 处理static下面静态文件的url
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),

    # users的url配置放到了app目录下
    url(r'^users/', include('users.urls', namespace='user')),

    # orginazitiom的url配置放到了app目录下
    url(r'^org/', include('organization.urls', namespace='org')),

    # courses的url配置放到了app目录下
    url(r'^courses/', include('courses.urls', namespace='course')),

    # operation 的url配置放到了app目录下
    url(r'^operation/', include('operation.urls', namespace='operation')),

]

# 配置 403 404 500 页面
handler403 = 'users.views.page_not_allow'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.server_error'

apps/courses/urls.py
from django.conf.urls import url, include

from .views import (CourseListView, CourseDetailView, CourseStudyView, CourseCommentView,
                    CourseAddcommentView, CourseVideoView)


urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='detail'),

    url(r'^study/(?P<course_id>\d+)/$', CourseStudyView.as_view(), name='study'),
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='comment'),
    url(r'^add_comment/$', CourseAddcommentView.as_view(), name='add_comment'),
    url(r'^video/(?P<video_id>.*?)/$', CourseVideoView.as_view(), name='video'),

]

apps/organization/urls.py
from django.conf.urls import url, include
from .views import (OrglistView, OrghomeView, OrgcourseView, OrgdescView, OrgteacherView, TeacherListView,
                    TeacherDetailView)


urlpatterns = [
    url(r'^list/$', OrglistView.as_view(), name='list'),
    url(r'^home/(?P<org_id>\d+)/$', OrghomeView.as_view(), name='home'),
    url(r'^courses/(?P<org_id>\d+)/$', OrgcourseView.as_view(), name='courses'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgdescView.as_view(), name='desc'),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgteacherView.as_view(), name='teacher'),

    # 配置teacher 相关页面
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),

]

apps/users/urls.py
from django.conf.urls import url

from .views import (LoginView, LogoutView, RegisterView, ActiveView, ForgetpwdView, ResetpwdView, UserInfoView,
                    UpdateImageView, UpdatePasswdView, UpdateEmailView, UserInfoCourseView, UserInfoFavCoursesView,
                    UserInfoFavOrgsView, UserInfoFavTeachersView, UserInfoMessageView)


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<active_code>.*)/$', ActiveView.as_view(), name='user_active'),
    url(r'^forget/$', ForgetpwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<reset_code>.*)/$', ResetpwdView.as_view(), name='reset_pwd'),

    # 用户中心的url配置
    url(r'^info/$', UserInfoView.as_view(), name='info'),   # 用户信息页面显示或修改
    url(r'^image/upload/$', UpdateImageView.as_view(), name='update_image'),  # 更新用户头像
    url(r'^passwd/update/$', UpdatePasswdView.as_view(), name='passwd_update'),  # 更新用户密码
    url(r'^email/update/$', UpdateEmailView.as_view(), name='email_update'),  # 获取邮箱验证码以及更新用户邮箱

    url(r'^user_courses/$', UserInfoCourseView.as_view(), name='user_courses'),  # 获取我的课程
    url(r'^user_fav_courses/$', UserInfoFavCoursesView.as_view(), name='user_fav_courses'),  # 获取我收藏的课程
    url(r'^user_fav_orgs/$', UserInfoFavOrgsView.as_view(), name='user_fav_orgs'),  # 获取我收藏的课程机构
    url(r'^user_fav_teachers/$', UserInfoFavTeachersView.as_view(), name='user_fav_teachers'),  # 获取我收藏的老师

    url(r'^message/$', UserInfoMessageView.as_view(), name='message'),  # 加载用户消息
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/users/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


# 定义一个user类，继承AbstractUser类，作用是扩展AbstractUser类， 在settings中用AUTH_USER_MODEL指定为用户验证的类
class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=64, default="coder", verbose_name="昵称")
    birthday = models.DateField(null=True, blank=True, verbose_name="生日")
    gender_choices = (
        ('male', '男'),
        ('female', '女'),
        ('other', '其他'),
    )
    gender = models.CharField(max_length=8, choices=gender_choices, default='other', verbose_name="性别")
    mobile = models.CharField(max_length=32, null=True, blank=True, verbose_name="电话")
    address = models.CharField(max_length=128, null=True, blank=True, verbose_name="地址")
    image = models.ImageField(
        upload_to='head_image/%Y/%m', max_length=128,
        default='head_image/default.png', verbose_name="头像")
    # ImageField 在数据库中保存的是图片的路径地址，也是CharField， 所以也要设置最大长度

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def get_unread_message_num(self):
        """ 获取用户的未读消息 在每个页面都要用到 所以绑定到request.user去 """
        from operation.models import UserMessage
        # 把导入放在是让在用的时候才导入，避免放在文件开头，那样会导致包的循环引用
        unread_message_num = UserMessage.objects.filter(user=self.id, has_read=False).count()
        return unread_message_num

    def __str__(self):
        return self.username


# 由于 邮箱验证码 和首页轮播图功能单一， 所以为了简便， 放在了users app 中
class EmailVerifyRecord(models.Model):
    email = models.EmailField(max_length=64, verbose_name="邮箱")
    code = models.CharField(max_length=32, verbose_name="邮箱验证码")
    send_type_choices = (
        ('register', '注册'),
        ('forget', '找回密码'),
        ('update_email', '找回密码'),
    )
    send_type = models.CharField(choices=send_type_choices, max_length=16, verbose_name="类型")
    send_time = models.DateTimeField(default=datetime.now, verbose_name="发送时间")

    class Meta:
        verbose_name = "邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.email
    #     return "{code}({email})".format(code=self.code, email=self.email)
        # 这里 是设置在后台显示哪些字段信息，不重载_str_， 默认是当前类的对象
        # 这里设置 跟 admin中注册时，list_display显示是一样的，不过list_display效果更好，一般设置那个，但是档有外键时，就需要设置了


class Banner(models.Model):
    title = models.CharField(max_length=256, verbose_name="标题")
    image = models.ImageField(max_length=128, upload_to='banner/%Y/%m', verbose_name="轮播图")
    url = models.URLField(max_length=256, verbose_name="访问地址")
    index = models.IntegerField(default=100, verbose_name="播放顺序")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "轮播图"
        verbose_name_plural = verbose_name

apps/users/views.py
import json

from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.generic import View
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from .models import UserProfile, EmailVerifyRecord, Banner
from .forms import LoginForm, RegisterForm, ForgetpwdForm, ResetpwdForm, UserImageForm, UserInfoForm
from utils.user_emails import email_send
from utils.mixin_utils import LoginRequiredMixin
from operation.models import UserCourse, UserFavorite, UserMessage
from courses.models import Course
from organization.models import CourseOrg, Teacher

# Create your views here.


class CustomBackends(ModelBackend):
    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            # django处理存在数据库中的密码是加密的，传递过来的密码是明文的，不能直接判断，要用这个函数来实现验证
            if user.check_password(password):
                return user
        except Exception as e:
            return None


class RegisterView(View):
    def get(self, request):
        register_form = RegisterForm()
        return render(request, 'register.html', {'register_form': register_form})

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            register_user = UserProfile()
            email = request.POST.get('email')
            if UserProfile.objects.filter(email=email):
                return render(request, 'register.html', {'msg': "用户已注册", 'register_form': register_form})

            register_user.username = email
            register_user.email = email
            password = request.POST.get('password')
            # 由于 django是存储的加密后的密码， 所以这里要先对前段传递的密码进行加密，再存入数据库
            # django.contrib.auth.hashers 下的 make_password 实现了对密码的加密
            register_user.password = make_password(password)
            register_user.is_active = False   # 这里注册时设置未激活，后面给邮箱激活链接

            status = email_send(email=request.POST.get('email'), send_type='register')
            if status:
                register_user.save()  # 如果邮件发送成功，调用 model 的save 方法，把注册的账号保存到数据库
                return redirect(reverse('index'))
            else:
                return render(request, 'register.html', {'msg': "邮箱验证失败，请重试"})
        else:
            return render(request, 'register.html', {'register_form': register_form})


class ActiveView(View):
    def get(self, request, active_code):
        email_record_objs = EmailVerifyRecord.objects.filter(code=active_code)  # 可能不唯一(几率很小) 所以不用get
        if email_record_objs:
            for email_record_obj in email_record_objs:
                # 对用户激活
                email = email_record_obj.email
                user = UserProfile.objects.get(email=email)
                user.is_active = True
                user.save()

                # 给用户发送欢迎消息
                message = "欢迎来到XMooc在线学习网，希望你能在接下来的日子学习到你想获得的知识"
                UserMessage.objects.create(user=user.id, message=message)

            return redirect(reverse('index'))
        else:
            return render(request, 'active_fail.html')


class LoginView(View):
    def get(self, request):
        return render(request, 'login.html', {})

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name = request.POST.get('username', '')
            pass_word = request.POST.get('password', '')
            user = authenticate(username=user_name, password=pass_word)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse('index'))
                else:
                    return render(request, 'login.html', {'msg': "用户未激活", 'login_form': login_form})
            else:
                return render(request, 'login.html', {'msg': "请输入正确的用户名或密码", 'login_form': login_form})
        else:
            return render(request, 'login.html', {'login_form': login_form})


class LogoutView(View):
    """
    用户退出登录
    """
    def get(self, request):
        logout(request)
        return redirect(reverse('index'))   # reverse 可以把url的名字转换成实际的相对路径


class ForgetpwdView(View):
    def get(self, request):
        forget_form = ForgetpwdForm()
        return render(request, 'forgetpwd.html', {'forget_form': forget_form})

    def post(self, request):
        forget_form = ForgetpwdForm(request.POST)
        if forget_form.is_valid():
            email = request.POST.get('email')
            users = UserProfile.objects.filter(email=email)
            # 原本email字段没有设置唯一，但注册时验证了，不存在才能注册，所以这里查询结果，若存在，那就只有一个
            if users:
                status = email_send(email=email, send_type='forget')
                if status:
                    return render(request, 'login.html', {'forget_form': forget_form})
                else:
                    return render(request, 'reset_pwd_msg.html', {'msg': "修改密码邮件发送失败，请重试"})
            else:
                return render(request, 'forgetpwd.html', {'forget_form': forget_form, 'msg': "账户不存在"})
        else:
            return render(request, 'forgetpwd.html', {'forget_form': forget_form})


class ResetpwdView(View):
    def get(self, request, reset_code):
        reset_form = ResetpwdForm()

        email_record_objs = EmailVerifyRecord.objects.filter(code=reset_code)
        if email_record_objs:
            for email_record in email_record_objs:
                email = email_record.email
                return render(request, 'password_reset.html',
                              {'reset_form': reset_form, 'email': email, 'code': reset_code})
        else:
            return render(request, 'reset_pwd_msg.html', {'msg': "你请求的链接有误，请重试"})

    def post(self, request, reset_code):
        reset_form = ResetpwdForm(request.POST)
        email = request.POST.get('email')
        email_record_objs = EmailVerifyRecord.objects.filter(code=reset_code, email=email)
        # 可以防止修改邮箱，导致 任意邮箱密码修改 的漏洞
        if reset_form.is_valid() and email_record_objs:
            pwd1 = request.POST.get('password1')
            pwd2 = request.POST.get('password1')
            if pwd1 != pwd2:
                return render(request, 'password_reset.html',
                    {'reset_form': reset_form, 'email': email, 'code': reset_code, 'msg': "两次密码不一致"})
            users = UserProfile.objects.filter(email=email)
            for user in users:
                user.password = make_password(pwd2)
                user.save()
            return redirect(reverse('user:login'))

        else:
            return render(request, 'reset_pwd_msg.html', {'msg': "你的请求存在问题，请确认后重试"})


class UserInfoView(LoginRequiredMixin, View):
    """
    用户中心 信息 显示 或修改
    """
    def get(self, request):
        """ 显示用户个人信息页面 """
        return render(request, 'usercenter-info.html', {})

    def post(self, request):
        """ 修改用户的 个人信息 """
        user_info_form = UserInfoForm(request.POST, instance=request.user)
        # 注意这里的 instance 参数， 有则代表更新，没有就是创建
        if user_info_form.is_valid():
            user_info_form.save()
            status = {'code': 0, 'msg': '更新成功'}
        else:
            status = {'code': 1, 'msg': user_info_form.errors}
        return HttpResponse(content=json.dumps(status), content_type="application/json")


class UpdateImageView(LoginRequiredMixin, View):
    """
    更新 用户头像
    """
    def post(self, request):
        # 注意这里验证form时， 需要把request.POST 和 request.FILES 都传递过来
        user_image_form = UserImageForm(request.POST, request.FILES, instance=request.user)
        if user_image_form.is_valid():
            user_image_form.save()
            status = {'code': 0, 'msg': '更新成功'}
        else:
            status = {'code': 0, 'msg': '更新失败'}
        return HttpResponse(content=json.dumps(status), content_type="application/json")


class UpdatePasswdView(View):
    """
    在个人中心更改用户密码
    """
    def post(self, request):
        rest_pwd_form = ResetpwdForm(request.POST)
        if rest_pwd_form.is_valid():
            pwd1 = request.POST.get('password1')
            pwd2 = request.POST.get('password2')
            if pwd1 != pwd2:
                status = {'code': 1, 'msg': '两次密码不一致'}
                return HttpResponse(content=json.dumps(status), content_type='application/json')
            request.user.password = make_password(pwd2)
            request.user.save()
            status = {'code': 0, 'msg': '修改密码成功'}
            return HttpResponse(content=json.dumps(status), content_type='application/json')
        else:
            return HttpResponse(content=json.dumps(rest_pwd_form.errors), content_type='application/json')


class UpdateEmailView(LoginRequiredMixin, View):
    """
    修改用户邮箱： 1、获取邮箱验证码 2、修改用户邮箱
    """
    def get(self, request):
        """ 获取邮箱验证码 """
        email = request.GET.get('email', '')
        if email and not UserProfile.objects.filter(email=email):
            status = email_send(email=email, send_type='update_email')
            if status:
                status = {'code': 0, 'msg': '邮箱验证码发送成功'}
            else:
                status = {'code': 1, 'msg': '邮箱验证码发送失败'}
        else:
            status = {'code': 1, 'msg': '当前邮箱已经存在'}
        return HttpResponse(content=json.dumps(status), content_type='application/json')

    def post(self, request):
        """ 修改用户的邮箱 """
        email = request.POST.get('email', '')
        code = request.POST.get('code', '')
        email_record_obj = EmailVerifyRecord.objects.filter(email=email, code=code, send_type='update_email')
        if email_record_obj:
            request.user.email = email
            request.user.save()

templates/users/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="3;url={% url 'index' %}">
    <title>Title</title>
</head>
<body>
<h2>当前链接失效，请输入正确的链接</h2>
</body>
</html>

templates/users/password_reset.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'user:reset_pwd' reset_code=code %}" method="post">{% csrf_token %}
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name="email" value="{{ email }}" />
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <div class="error btns" id="jsForgetTips">{{ msg }}</div>
                <li class="button">
{#                    <input type="button" value="提交" onclick="reset_password_form_submit()">#}
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                </li>
            </ul>
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/users/reset_pwd_msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>重置密码</title>
</head>
<body>
    <h2>{{ msg }}</h2>
</body>
</html>

templates/users/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load static %}

{% block custom_title %} 我的收藏- XMooc在线学习网 {% endblock %}

{% block custom_bread %} 我的收藏 {% endblock %}


{% block custom_right %}
    <div class="right" >
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'user:user_fav_courses' %}">公开课程</a></li>
                    <li><a href="{% url 'user:user_fav_orgs' %}">课程机构</a> </li>
                    <li><a href="{% url 'user:user_fav_teachers' %}">授课教师 </a></li>
                </ul>

            </div>
            <div class="companycenter">
                <div class="group_list brief">
                    {% for course in courses.object_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="pageturn">
                    <ul class="pagelist">
                        {% if courses.has_previous %}
                            <li class="long"><a href="?{{ courses.previous_page_number.querystring }}" >上一页</a></li>
                        {% endif %}
                        {% for page in courses.pages %}
                            {% if page %}
                                {% ifequal page courses.number %}
                                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="none"><a href="">...</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if courses.has_next %}
                            <li class="long"><a href="?{{ courses.next_page_number.querystring }}">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/users/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load static %}

{% block custom_title %} 我的收藏- XMooc在线学习网 {% endblock %}

{% block custom_bread %} 我的收藏 {% endblock %}


{% block custom_right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:user_fav_courses' %}">公开课程</a></li>
                        <li class="active"><a href="{% url 'user:user_fav_orgs' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:user_fav_teachers' %}">授课教师 </a></li>
                    </ul>
                </div>
                <div class="messagelist">
                {% for org in orgs.object_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.images }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                    <img src="{% static 'images/authentication.png' %}"/>
                                    <img src="{% static 'images/gold.png' %}"/>
                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                {% endfor %}
                </div>
                <div class="pageturn">
                    <ul class="pagelist">
                        {% if orgs.has_previous %}
                            <li class="long"><a href="?{{ orgs.previous_page_number.querystring }}" >上一页</a></li>
                        {% endif %}
                        {% for page in orgs.pages %}
                            {% if page %}
                                {% ifequal page orgs.number %}
                                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="none"><a href="">...</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if orgs.has_next %}
                            <li class="long"><a href="?{{ orgs.next_page_number.querystring }}">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
{% endblock %}

templates/users/usercenter-fav-teacher.html
{% extends 'usercenter-base.html' %}
{% load static %}

{% block custom_title %} 我的收藏- XMooc在线学习网 {% endblock %}

{% block custom_bread %} 我的收藏 {% endblock %}


{% block custom_right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:user_fav_courses' %}">公开课程</a></li>
                        <li><a href="{% url 'user:user_fav_orgs' %}">课程机构</a> </li>
                        <li class="active"><a href="{% url 'user:user_fav_teachers' %}">授课教师 </a></li>
                    </ul>
                </div>
                <div class="messagelist">
                {% for teacher in teachers.object_list %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'org:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.user.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'org:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_years }}年</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.get_courses }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    </div>
                {% endfor %}
                </div>
                <div class="pageturn">
                        <ul class="pagelist">
                            {% if teachers.has_previous %}
                                <li class="long"><a href="?{{ teachers.previous_page_number.querystring }}" >上一页</a></li>
                            {% endif %}
                            {% for page in teachers.pages %}
                                {% if page %}
                                    {% ifequal page teachers.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="none"><a href="">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if teachers.has_next %}
                                <li class="long"><a href="?{{ teachers.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}